use_frameworks!

platform :ios, '9.0'

target 'KrNrImagePicker_Example' do
  pod 'KrNrImagePicker', :path => '../'

  target 'KrNrImagePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
